### PR TITLE
ESlint

### PR DESCRIPTION
**Pull request by TheSuperGamer20578**
# Checklist

- [ ] This PR has been tested
	- [ ] Everything still works
	- [ ] No major bugs have been made
		- [ ] I have listed minor bugs that have been added
- [ ] I have listed all changes that this PR makes
- [ ] This PR needs no further work
- [ ] Manual restart and/or configuration required post-merge

- [ ] This is a major change
- [x] This is a minor change
<p/>

- [ ] This is a bug fix
- [ ] This is an enhancement or new feature
- [x] Other: GH actions change

### CODE REVIEW

**Comment by TheSuperGamer20578** [comment]
@ogxn pls review so that I know its correct

**Comment by ogxn** [comment]
line 19 says pylint; otherwise fine

**Comment by TheSuperGamer20578** [comment]
> line 19 says pylint; otherwise fine

you do reviews in files changed tab

**Comment by ogxn** [comment]
thank you for telling me that hold on

**Review by ogxn — APPROVED** [review]

**Comment by TheSuperGamer20578** [comment]
there is no comment is it ready for merge?

**Comment by ogxn** [comment]
i mean i approved it so yes

**Pull request merged**
