### PR TITLE
Grammar (and some dashboard stuff for whatever reason)

### PR DESCRIPTION
**Pull request by ogxn**
fixed grammar. some of the dashboard-frontend commits also pushed here?

# Checklist

- [ ] This PR has been tested
	- [ ] Everything still works
	- [ ] No major bugs have been made
		- [ ] I have listed minor bugs that have been added
- [ ] I have listed all changes that this PR makes
- [ ] This PR needs no further work
- [ ] Manual restart and/or configuration required post-merge
- [ ] README.md or other documentation will be updated by this PR
- [ ] I have listed how to make bot work again post-merge 

- [ ] This is a major change
- [x] This is a minor change
<p/>

- [ ] This is a bug fix
- [ ] This is an enhancement or new feature
- [x] Other: grammar fixes in code

### CODE REVIEW

**Comment by TheSuperGamer20578** [comment]
> problem: frontend/.babelrc.js should only be there to convert the JSX. frontend/.babelrc.output.js is for transpiling to earlier versions of ECMAScript
> 
> edit: TypeScript automatically transpiles JSX anyway, nevermind

@ogxn if this pr is not done set it as a draft

**Comment by TheSuperGamer20578** [comment]
also you didnt tick the no more work needed box

**Comment by TheSuperGamer20578** [comment]
why close?

**Comment by ogxn** [comment]
because all of the commits from dashboard-frontend were pushed to grammar

**Comment by TheSuperGamer20578** [comment]
you can reopen and do `git rebase -i HEAD~9` and then it will give you the option to pick or drop commits and then do `git push -f`

**Comment by ogxn** [comment]
I'm gonna just redo this with a new branch

**Pull request closed without merging**
